apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-console-plugin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuadrant-console-plugin
  namespace: kuadrant-console-plugin
  labels:
    app: kuadrant-console-plugin
    app.kubernetes.io/component: kuadrant-console-plugin
    app.kubernetes.io/instance: kuadrant-console-plugin
    app.kubernetes.io/name: kuadrant-console-plugin
    app.kubernetes.io/part-of: kuadrant-console-plugin
    app.openshift.io/runtime-namespace: kuadrant-console-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuadrant-console-plugin
  template:
    metadata:
      labels:
        app: kuadrant-console-plugin
        app.kubernetes.io/component: kuadrant-console-plugin
        app.kubernetes.io/instance: kuadrant-console-plugin
        app.kubernetes.io/name: kuadrant-console-plugin
        app.kubernetes.io/part-of: kuadrant-console-plugin
    spec:
      containers:
      - name: kuadrant-console-plugin
        image: quay.io/kuadrant/console-plugin:latest
        ports:
        - containerPort: 9443
          protocol: TCP
        imagePullPolicy: Always
        env:
          - name: TOPOLOGY_CONFIGMAP_NAME
            value: topology
          - name: TOPOLOGY_CONFIGMAP_NAMESPACE
            value: kuadrant-system
        volumeMounts:
        - name: plugin-serving-cert
          readOnly: true
          mountPath: /var/serving-cert
        - name: nginx-conf
          readOnly: true
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: plugin-serving-cert
        secret:
          secretName: plugin-serving-cert
          defaultMode: 420
      - name: nginx-conf
        configMap:
          name: nginx-conf
          defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: kuadrant-console-plugin
  labels:
    app: kuadrant-console-plugin
    app.kubernetes.io/component: kuadrant-console-plugin
    app.kubernetes.io/instance: kuadrant-console-plugin
    app.kubernetes.io/name: kuadrant-console-plugin
    app.kubernetes.io/part-of: kuadrant-console-plugin
data:
  nginx.conf: |
    error_log /dev/stdout;
    events {}
    http {
      access_log         /dev/stdout;
      include            /etc/nginx/mime.types;
      default_type       application/octet-stream;
      keepalive_timeout  65;

      server {
        listen              9443 ssl;
        listen              [::]:9443 ssl;
        ssl_certificate     /var/serving-cert/tls.crt;
        ssl_certificate_key /var/serving-cert/tls.key;

        add_header oauth_token "$http_Authorization";

        location / {
          root                /usr/share/nginx/html;
        }

        # Serve config.js from /tmp
        location /config.js {
          root /tmp;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
  name: kuadrant-console-plugin
  namespace: kuadrant-console-plugin
  labels:
    app: kuadrant-console-plugin
    app.kubernetes.io/component: kuadrant-console-plugin
    app.kubernetes.io/instance: kuadrant-console-plugin
    app.kubernetes.io/name: kuadrant-console-plugin
    app.kubernetes.io/part-of: kuadrant-console-plugin
spec:
  ports:
  - name: 9443-tcp
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app: kuadrant-console-plugin
  type: ClusterIP
  sessionAffinity: None
---
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: kuadrant-console-plugin
spec:
  displayName: 'Kuadrant Console Plugin'
  service:
    name: kuadrant-console-plugin
    namespace: kuadrant-console-plugin
    port: 9443
    basePath: '/'

