# SA and RBAC for running the console with impersonation support
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-console
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-console-admin
subjects:
  - kind: ServiceAccount
    name: openshift-console
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# allow the console SA to impersonate users for RBAC testing
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-impersonator
rules:
  - apiGroups: [""]
    resources: ["users", "groups", "serviceaccounts"]
    verbs: ["impersonate"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["userextras/scopes.authorization.openshift.io"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-impersonator
subjects:
  - kind: ServiceAccount
    name: openshift-console
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: console-impersonator
  apiGroup: rbac.authorization.k8s.io
