import * as React from 'react';
import '@testing-library/jest-dom';
import { fireEvent, render, screen, within } from '@testing-library/react';
import { ResourceFilterToolbar } from './ResourceFilterToolbar';

jest.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, values: Record<string, string | number> = {}) =>
      key.replace(/{{(\w+)}}/g, (_, name) => String(values[name])),
  }),
}));

beforeEach(() => {
  jest.replaceProperty(window, 'innerWidth', 1440);
});

afterEach(() => jest.restoreAllMocks());

it('keeps filter labels separate from IDs generated by the host console', () => {
  const onDeleteGroup = jest.fn();
  const onDeleteNamespace = jest.fn();
  const content = (selectedResourceTypes: string[]) => (
    <>
      <div id="pf-random-id-0">Console user menu</div>
      <div id="pf-random-id-1">Console navigation</div>
      <ResourceFilterToolbar
        allResourceTypes={['Gateway', 'HTTPRoute']}
        selectedResourceTypes={selectedResourceTypes}
        allNamespaces={['kuadrant-test']}
        selectedNamespace="kuadrant-test"
        onSelect={jest.fn()}
        onNamespaceSelect={jest.fn()}
        onDeleteFilter={jest.fn()}
        onDeleteGroup={onDeleteGroup}
        onDeleteNamespace={onDeleteNamespace}
        onClearAll={jest.fn()}
      />
    </>
  );
  const { rerender } = render(content(['Gateway']));

  const resourceGroup = screen.getByRole('list', { name: 'Resource' });
  const namespaceGroup = screen.getByRole('list', { name: 'Namespace' });
  const resourceLabelId = resourceGroup.getAttribute('aria-labelledby');
  const namespaceLabelId = namespaceGroup.getAttribute('aria-labelledby');
  expect(resourceLabelId).not.toBe(namespaceLabelId);
  for (const id of [resourceLabelId, namespaceLabelId]) {
    expect(document.querySelectorAll(`[id="${id}"]`)).toHaveLength(1);
  }

  fireEvent.click(screen.getByRole('button', { name: 'Close label group Resource' }));
  fireEvent.click(screen.getByRole('button', { name: 'Close label group Namespace' }));
  expect(onDeleteGroup).toHaveBeenCalledTimes(1);
  expect(onDeleteNamespace).toHaveBeenCalledTimes(1);

  rerender(content(['Gateway', 'HTTPRoute']));
  expect(screen.getByRole('list', { name: 'Resource' })).toHaveAttribute(
    'aria-labelledby',
    resourceLabelId,
  );
  expect(screen.getByRole('list', { name: 'Namespace' })).toHaveAttribute(
    'aria-labelledby',
    namespaceLabelId,
  );
});

it('keeps individual removal, overflow, empty groups, and reset working', () => {
  const onDeleteFilter = jest.fn();
  const onClearAll = jest.fn();
  const resourceTypes = ['Gateway', 'HTTPRoute', 'AuthPolicy', 'DNSPolicy'];
  const content = (selectedResourceTypes: string[]) => (
    <ResourceFilterToolbar
      allResourceTypes={resourceTypes}
      selectedResourceTypes={selectedResourceTypes}
      onSelect={jest.fn()}
      onDeleteFilter={onDeleteFilter}
      onDeleteGroup={jest.fn()}
      onClearAll={onClearAll}
    />
  );
  const { rerender } = render(content([...resourceTypes, 'Gateway']));
  const group = screen.getByRole('list', { name: 'Resource' });
  expect(within(group).getAllByText('Gateway')).toHaveLength(1);
  expect(within(group).queryByText('DNSPolicy')).not.toBeInTheDocument();
  fireEvent.click(within(group).getByRole('button', { name: '1 more' }));
  expect(within(group).getByText('DNSPolicy')).toBeVisible();
  fireEvent.click(within(group).getByRole('button', { name: 'Close DNSPolicy' }));
  expect(onDeleteFilter).toHaveBeenCalledWith('Resource', 'DNSPolicy');
  fireEvent.click(within(group).getByRole('button', { name: 'Show Less' }));
  expect(within(group).queryByText('DNSPolicy')).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Reset Filters' }));
  expect(onClearAll).toHaveBeenCalledTimes(1);

  rerender(content([]));
  expect(screen.queryByRole('list', { name: 'Resource' })).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'Reset Filters' })).not.toBeInTheDocument();
  rerender(content(['Gateway']));
  expect(screen.getByRole('list', { name: 'Resource' })).toBeVisible();
});

it('only shows a namespace label when namespace filtering is available', () => {
  const onDeleteNamespace = jest.fn();
  const content = (allNamespaces?: string[]) => (
    <ResourceFilterToolbar
      allResourceTypes={['Gateway']}
      selectedResourceTypes={[]}
      allNamespaces={allNamespaces}
      selectedNamespace="kuadrant-test"
      onSelect={jest.fn()}
      onNamespaceSelect={jest.fn()}
      onDeleteFilter={jest.fn()}
      onDeleteGroup={jest.fn()}
      onDeleteNamespace={onDeleteNamespace}
      onClearAll={jest.fn()}
    />
  );
  const { rerender } = render(content(['kuadrant-test']));
  fireEvent.click(screen.getByRole('button', { name: 'Close kuadrant-test' }));
  expect(onDeleteNamespace).toHaveBeenCalledTimes(1);
  rerender(content());
  expect(screen.queryByRole('list', { name: 'Namespace' })).not.toBeInTheDocument();
  expect(screen.queryByRole('button', { name: 'Reset Filters' })).not.toBeInTheDocument();
});
