import * as React from 'react';
import '@testing-library/jest-dom';
import { fireEvent, render, screen } from '@testing-library/react';
import { ResourceFilterToolbar } from './ResourceFilterToolbar';

jest.mock('react-i18next', () => ({
  useTranslation: () => ({ t: (key: string) => key }),
}));

beforeEach(() => {
  jest.replaceProperty(window, 'innerWidth', 1440);
});

afterEach(() => jest.restoreAllMocks());

it('keeps filter labels separate from IDs generated by the host console', () => {
  const onDeleteGroup = jest.fn();
  const onDeleteNamespace = jest.fn();
  const content = (selectedResourceTypes: string[]) => (
    <>
      <div id="pf-random-id-0">Console user menu</div>
      <div id="pf-random-id-1">Console navigation</div>
      <ResourceFilterToolbar
        allResourceTypes={['Gateway', 'HTTPRoute']}
        selectedResourceTypes={selectedResourceTypes}
        allNamespaces={['kuadrant-test']}
        selectedNamespace="kuadrant-test"
        onSelect={jest.fn()}
        onNamespaceSelect={jest.fn()}
        onDeleteFilter={jest.fn()}
        onDeleteGroup={onDeleteGroup}
        onDeleteNamespace={onDeleteNamespace}
        onClearAll={jest.fn()}
      />
    </>
  );
  const { rerender } = render(content(['Gateway']));

  const resourceGroup = screen.getByRole('list', { name: 'Resource' });
  const namespaceGroup = screen.getByRole('list', { name: 'Namespace' });
  const resourceLabelId = resourceGroup.getAttribute('aria-labelledby');
  const namespaceLabelId = namespaceGroup.getAttribute('aria-labelledby');
  expect(resourceLabelId).not.toBe(namespaceLabelId);
  for (const id of [resourceLabelId, namespaceLabelId]) {
    expect(document.querySelectorAll(`[id="${id}"]`)).toHaveLength(1);
  }

  fireEvent.click(screen.getByRole('button', { name: 'Close label group Resource' }));
  fireEvent.click(screen.getByRole('button', { name: 'Close label group Namespace' }));
  expect(onDeleteGroup).toHaveBeenCalledTimes(1);
  expect(onDeleteNamespace).toHaveBeenCalledTimes(1);

  rerender(content(['Gateway', 'HTTPRoute']));
  expect(screen.getByRole('list', { name: 'Resource' })).toHaveAttribute(
    'aria-labelledby',
    resourceLabelId,
  );
  expect(screen.getByRole('list', { name: 'Namespace' })).toHaveAttribute(
    'aria-labelledby',
    namespaceLabelId,
  );
});
