name: Contributor Governance

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request_target:
    types: [opened, reopened]

jobs:
  governance:
    uses: Kuadrant/.github/.github/workflows/contributor-governance.yml@3c40fafa32814a5c7cdc92e409e8d5b0160c9360 # ratchet:Kuadrant/.github/.github/workflows/contributor-governance.yml@main
    secrets: inherit
