name: Contributor Governance

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request_target:
    types: [opened, reopened]

jobs:
  governance:
    uses: Kuadrant/.github/.github/workflows/contributor-governance.yml@2f04849af72d4a474e534392a268d056b253b00e # ratchet:Kuadrant/.github/.github/workflows/contributor-governance.yml@main
    secrets: inherit
