name: E2E Tests

on:
  pull_request:
    branches: [main]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-smoke:
    uses: ./.github/workflows/e2e-common.yaml
    with:
      suite: smoke
