name: Build and Push Versioned Image

on:
  release:
    types: [published]

env:
  REGISTRY_USER: ${{ secrets.QUAY_USER }}
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

jobs:
  release:
    name: Build and push versioned image
    runs-on: ubuntu-22.04

    steps:
      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - uses: actions/checkout@v4

      - name: Build Image for Release
        id: build-release-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/kuadrant/console-plugin
          tags: |
            ${{ github.event.release.tag_name }}
          containerfiles: |
            ./Dockerfile

      - name: Push To Quay.io for Release
        id: push-release-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: quay.io
          image: kuadrant/console-plugin
          tags: |
            ${{ github.event.release.tag_name }}

      - name: Print image URL for Release
        run: echo "Versioned image pushed to ${{ steps.push-release-to-quay.outputs.registry-paths }}"
